var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b,c){if(!c||null!=a){c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]}};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(f,g){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.polyfill("Math.sign",function(a){return a?a:function(b){b=Number(b);return 0===b||isNaN(b)?b:0<b?1:-1}},"es6","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).i}},"es6","es3");
function GameStorage(a){this.works=!0;this.tempStorage={};try{if(!localStorage.getItem("version")&&(localStorage.setItem("version",a),!localStorage.getItem("version")))throw"grenade";}catch(b){this.works=!1}this.works?Number(localStorage.getItem("version"))!==a&&(localStorage.clear(),console.log("Storage cleared because of game update to version "+a)):this.setItem("version",a)}
GameStorage.prototype.setItem=function(a,b){b=JSON.stringify(b);this.works?localStorage.setItem(a,b):this.tempStorage[a]=b};GameStorage.prototype.removeItem=function(a){this.works?localStorage.removeItem(a):delete this.tempStorage[a]};GameStorage.prototype.getItem=function(a){return this.works?JSON.parse(localStorage.getItem(a)):this.tempStorage[a]?JSON.parse(this.tempStorage[a]):null};var DEBUG=!0,RIGHT=0,LEFT=1,NOT_FALLING=0,IN_JUMP=1,FALLING=2,GAME_WIDTH=800,GAME_HEIGHT=600,FIRST_LEVEL="level1.js",LEVEL_DIR="levels/",STORAGE_NO_AUDIO="no_audio",STORAGE_LEVEL="last_level",STORAGE_STATE="state";window.addEventListener("load",function(){var a=new GameEngine;DEBUG&&"localhost"===location.host&&window.LevelEditor&&new LevelEditor(a)},!1);
function GameEngine(){this.version=.02;this.width=GAME_WIDTH;this.height=GAME_HEIGHT;this.keysDown=[0,0,0];this.storage=new GameStorage(this.version);this.storage.works||dbg_warn("localStorage not supported. Your game will not be saved.");this.keyboard=new KeyboardManager(this);this.renderer=new GameRenderer(this);this.audio=new AudioManager(!this.storage.getItem(STORAGE_NO_AUDIO));this.audio.works||dbg_warn("Your browser does not support HTML5 audio or ogg/vorbis");this.posY=this.posX=this.viewportY=
this.viewportX=null;this.lastTick=Date.now();this.totalDelta=0;this.running=this.drawableObjects=this.blockingObjects=this.triggeringObjects=this.objectMap=this.objects=this.charBitmap=this.vspeed=this.direction=this.canJump=this.fallingState=this.tickCount=null;this.tickFunctionStopped=!0;this.isMoving=null;this.images={};this.drawHooks=this.gameData=null;this.levelFile=this.storage.getItem(STORAGE_LEVEL);var a=this;document.getElementById("mute_button").addEventListener("click",function(){a.toggleMute()},
!1);document.getElementById("reset_save").addEventListener("click",function(){a.nextLevel(FIRST_LEVEL)},!1);this.levelFile||(this.levelFile=FIRST_LEVEL);this.loadLevel(this.levelFile)}GameEngine.prototype.nextLevel=function(a){this.levelFile=a;this.storage.setItem(STORAGE_LEVEL,a);this.storage.removeItem(STORAGE_STATE);this.loadLevel(a)};
GameEngine.prototype.loadLevel=function(a){var b=this;this.running=!1;http_get(LEVEL_DIR+a+"?"+Math.random(),function(c){c=eval(c);if(!c)throw"level not found";b.level=c;b.loadResources(c)})};
GameEngine.prototype.loadResources=function(a){function b(){f++;return function(){g++;h.renderer.drawLoadingScreen(g,f);f===g&&h.start()}}function c(){throw"loading a resource failed. Will not start";}var d=a.resourceDir,e=Object.keys(a.images),f=0,g=0,h=this;this.audio.path=a.musicDir;this.level=a;this.audio.preload(this.level.jumpMusic1,b(),c);this.audio.preload(this.level.jumpMusic2,b(),c);e.forEach(function(k){var l=a.images[k],m=new Image;h.images[k]=m;m.onload=b();m.onerror=c;m.src=d+l});this.renderer.drawLoadingScreen(0,
f)};GameEngine.prototype.start=function(){this.charBitmap=Bitmap.fromImage(this.images.charHitmap);this.dead=!1;this.audio.play(this.level.backgroundMusic,!0,!0);this.restart();this.running=!0;this.tickFunctionStopped&&this.doTick(this)};
GameEngine.prototype.restart=function(){this.viewportX=this.level.startViewport.x;this.viewportY=this.level.startViewport.y;this.posX=this.level.startPosition.x;this.posY=this.level.startPosition.y;this.fallingState=FALLING;this.direction=RIGHT;this.canJump=this.isMoving=this.dead=!1;this.vspeed=0;this.audio.stop(this.level.deathMusic);this.tickCount=0;this.gameData={};this.drawHooks=[];this.loadObjects();var a=this.storage.getItem(STORAGE_STATE);a&&this.level.loadState(this,a);this.level.init(this)};
GameEngine.prototype.saveState=function(a){this.storage.setItem(STORAGE_STATE,a)};
GameEngine.prototype.loadObjects=function(){var a=this,b=Object.deepcopy(this.level.objects);this.objects=[];this.objectMap={};this.triggeringObjects=[];this.blockingObjects=[];this.drawableObjects=[];b=b.concatMap(function(d){return cartesianProductOnObjects(d.position,["x","y"]).map(function(e){var f=Object.deepcopy(d);f.x=e.x;f.y=e.y;return f})});var c={};b.forEach(function(d){d=a.addObject(d,c);d.init&&d.init(a)});b=this.drawableObjects.partition(function(d){return d.dynamic});this.drawableObjects=
b[0];this.renderer.loadBackground(b[1]);this.renderer.loadForeground([])};
GameEngine.prototype.addObject=function(a,b){var c=a.dynamic||!!a.id,d=a.shape,e=a.trigger,f=void 0,g=void 0,h=void 0,k=void 0,l="x y dynamic trigger image blocking killing id tickFunction zIndex position shape retrigger init".split(" ");b=b||{};Object.keys(a).deleteList(l).length&&(console.log(Object.keys(a).deleteList(l)),dbg_assert(!1,"Unkown properties"));a.image&&(f=this.images[a.image],dbg_assert(f,"invalid image id"),g=f.width,h=f.height);dbg_assert(!a.blocking||!e,"an object cannot block and have a trigger at the same time");
a.killing&&(dbg_assert(!e,"an object cannot kill and have a trigger at the same time"),dbg_assert(!a.blocking,"an object cannot kill and block at the same time"),e=this.die.bind(this));void 0===d&&f&&(e||a.blocking||c)&&(b[a.image]?d=b[a.image]:b[a.image]=d=new AutoShape(f));d&&(g=d.width,h=d.height,k=d.getBitmap());b={x:a.x,y:a.y,width:g,height:h,dynamic:c,visible:!0,image:f,bitmap:k,trigger:e,zIndex:a.zIndex||0,retrigger:!!a.retrigger,tickFunction:a.tickFunction,init:a.init};e&&(dbg_assert(e instanceof
Function,"trigger has to be a function"),dbg_assert(d,"objects that kill or have a trigger require a shape"),this.triggeringObjects.push(b));a.image&&this.drawableObjects.push(b);a.blocking&&(dbg_assert(d,"objects that block require a shape"),this.blockingObjects.push(b));this.objects.push(b);a.id&&(dbg_assert(!this.objectMap[a.id],"id used twice"),this.objectMap[a.id]=b);return b};
GameEngine.prototype.removeObject=function(a){this.objects=this.objects.delete(a);this.blockingObjects=this.blockingObjects.delete(a);this.drawableObjects=this.drawableObjects.delete(a);this.triggeringObjects=this.triggeringObjects.delete(a);a.id&&delete this.objectMap[a.id]};GameEngine.prototype.removeObjectById=function(a){(a=this.objectMap[a])&&this.removeObject(a)};GameEngine.prototype.toggleMute=function(){this.audio.toggleMute();this.audio.muted?this.storage.setItem(STORAGE_NO_AUDIO,1):this.storage.removeItem(STORAGE_NO_AUDIO)};
GameEngine.prototype.die=function(){this.dead||(this.audio.play(this.level.deathMusic,!1,!0,.3),this.dead=!0)};GameEngine.prototype.crush=function(){console.log("death by crushing");this.die()};
GameEngine.prototype.doTick=function doTick(a){a.tickFunctionStopped=!1;if(a.running){var c=a.level,d=Date.now();a.totalDelta+=d-a.lastTick;a.lastTick=d;500<=a.totalDelta&&(a.totalDelta=0);for(;a.totalDelta>=c.physics.timePerTick;)a.tick(a),a.totalDelta-=c.physics.timePerTick;a.renderer.redraw();a.drawHooks.forEach(function(e){e.call(a.level,a)});requestAnimationFrame(function(){doTick(a)})}else a.tickFunctionStopped=!0};
GameEngine.prototype.tick=function(a){var b=a.level.physics,c=a.keyboard.keyWasPressed;a.level.tickFunction(a);a.objects.forEach(function(d){d.tickFunction&&d.tickFunction.call(d,a);if(d.bitmap&&d.trigger){var e=a.characterCollision(d.bitmap,d.x,d.y);!e||!d.retrigger&&d.triggered||d.trigger.call(d,a);d.triggered=e}});a.tickCount++;a.dead||(!c[KEY_LEFT]!==!c[KEY_RIGHT]?(a.isMoving=!0,c[KEY_LEFT]?(a.moveCharacterRight(-b.moveSpeed),a.direction=LEFT):c[KEY_RIGHT]&&(a.moveCharacterRight(b.moveSpeed),
a.direction=RIGHT)):a.isMoving=!1,a.keysDown[1]=c[KEY_JUMP]?1:0,a.keysDown[2]=c[KEY_RIGHT]?1:0,a.keysDown[0]=c[KEY_LEFT]?1:0,a.fallingState===NOT_FALLING?(c[KEY_JUMP]&&(a.audio.play(a.level.jumpMusic1,!1,!1,.6),a.fallingState=IN_JUMP,a.canJump=!0,a.vspeed=b.jumpInitialSpeed,a.jumpTicks=b.jumpTicks),a.moveCharacterDown(1)||(a.fallingState=FALLING,a.canJump=!0)):(a.fallingState===IN_JUMP?(a.vspeed+=b.jumpGravity,a.jumpTicks--,c[KEY_JUMP]&&0!==a.jumpTicks||(a.fallingState=FALLING)):(a.canJump&&c[KEY_JUMP]&&
(a.audio.play(a.level.jumpMusic2,!1,!1,.6),a.fallingState=IN_JUMP,a.canJump=!1,a.vspeed=b.jumpInitialSpeed/1.5,a.jumpTicks=b.jumpTicks),a.vspeed=a.vspeed<b.fallSpeedCap?a.vspeed+b.fallGravity:b.fallSpeedCap),a.moveCharacterDown(Math.roundInfinity(a.vspeed))&&(0<a.vspeed?(a.fallingState=NOT_FALLING,a.vspeed=0,c[KEY_JUMP]=!1):a.vspeed=0)))};GameEngine.prototype.addDrawHook=function(a){this.drawHooks.push(a)};
GameEngine.prototype.moveCharacterRight=function(a){if(!this.charBitmap.compareMany(this.blockingObjects,this.posX+a,this.posY))return this.posX+=a,!1;for(var b=Math.sign(a);a;)if(this.posX+=b,a-=b,this.charBitmap.compareMany(this.blockingObjects,this.posX,this.posY))return this.posX-=b,!0;return!1};
GameEngine.prototype.moveCharacterDown=function(a){if(!this.charBitmap.compareMany(this.blockingObjects,this.posX,this.posY+a))return this.posY+=a,!1;for(var b=Math.sign(a);a;)if(this.posY+=b,a-=b,this.charBitmap.compareMany(this.blockingObjects,this.posX,this.posY))return this.posY-=b,!0;return!1};
GameEngine.prototype.characterCollision=function(a,b,c){return b>this.posX+this.level.characterWidth||c>this.posY+this.level.characterHeight||b+a.width<this.posX||c+a.height<this.posY?!1:this.charBitmap.compare(a,Math.round(b-this.posX),Math.round(c-this.posY))};
GameEngine.prototype.moveObjectRight=function(a,b){var c=Math.sign(b),d=!1;for(this.characterCollision(a.bitmap,a.x,a.y-1)&&(d=!0);b;)b-=c,a.x+=c,d?this.moveCharacterRight(c):this.characterCollision(a.bitmap,a.x,a.y)&&this.moveCharacterRight(c)&&(console.log("crushed"),this.die())};
GameEngine.prototype.moveObjectDown=function(a,b){if(0<=b){var c=!1;for(this.characterCollision(a.bitmap,a.x,a.y-1)&&(c=!0);b;)a.y++,b--,c?this.moveCharacterDown(1):this.characterCollision(a.bitmap,a.x,a.y)&&this.moveCharacterDown(1)&&(console.log("crushed"),this.die())}else for(;b;)b++,a.y--,this.characterCollision(a.bitmap,a.x,a.y)&&this.moveCharacterDown(-1)&&(console.log("crushed"),this.die())};function AudioManager(a){this.muted=!a;this.works=!0;window.Audio?(new Audio).canPlayType("audio/ogg; codecs=vorbis")||(this.works=!1):this.works=!1;this.playing=[];this.playQueue=[]}
AudioManager.prototype.play=function(a,b,c,d,e){if(this.works)if(this.muted)this.playQueue.push([new Date,Array.toArray(arguments)]);else{var f=this.playing.filter(Function.byIndex("file",a)).find(function(h){return(h.audio.ended||h.audio.paused)!=!!c});if(f)var g=f.audio;else g=new Audio(this.path+a),this.playing.push({audio:g,file:a});f=!1;void 0!==e?g.duration&&g.duration<e&&(f=!0):e=0;f||(void 0!==d&&(g.volume=d),4>g.readyState?g.addEventListener("loadedmetadata",function(){g.currentTime=e}):
g.currentTime=e,g.loop=b,g.play())}};AudioManager.prototype.preload=function(a,b,c){if(this.works&&!this.muted)if(this.playing.find(Function.byIndex("file",a)))b&&setTimeout(b,0);else{var d=new Audio(this.path+a);d.muted=this.muted;b&&(d.addEventListener("canplaythrough",b),c&&d.addEventListener("error",c));d.load();this.playing.push({audio:d,file:a});return d}else setTimeout(b,0)};
AudioManager.prototype.stop=function(a){function b(c){c.audio.pause()}this.works&&this.playing.filter(Function.byIndex("file",a)).forEach(b)};AudioManager.prototype.toggleMute=function(){function a(d){d.audio.muted=b}if(this.works){var b=this.muted=!this.muted;this.playing.forEach(a)}if(!this.muted){var c=this;this.playQueue.forEach(function(d){d[1][4]=(Date.now()-d[0])/1E3;c.play.apply(c,d[1])});this.playQueue=[]}};function Bitmap(a,b){this.width=a;this.height=b;this.count=a*b;this.data=new Uint8Array(this.count)}Bitmap.fromImage=function(a){var b=a.width,c=a.height,d=new Bitmap(b,c),e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;f.clearRect(0,0,b,c);f.drawImage(a,0,0);a=f.getImageData(0,0,b,c).data;for(b=0;b<d.count;b++)d.data[b]=0<a[4*b+3]|0;return d};
Bitmap.prototype.withOtherRect=function(a,b,c,d,e){b=this.getIntersection(a,b,c,d);c=b.otherY*a+b.otherX;d=b.thisY*this.width+b.thisX;for(var f=0;f<b.height;f++){for(var g=0;g<b.width;g++)e(b.otherX+g,b.otherY+f,this.data[d]),c++,d++;c+=a-b.width;d+=this.width-b.width}};Bitmap.prototype.stringify=function(){for(var a="Bitmap  width="+this.width+" height="+this.height+"\n",b=0;b<this.height;b++){for(var c=0;c<this.width;c++)a+=String(this.data[b*this.width+c]);a+="\n"}return a};
Bitmap.prototype.set=function(a,b,c){0<=a&&0<=b&&a<this.width&&b<this.height&&(this.data[b*this.width+a]=c)};Bitmap.prototype.copy=function(){return{__proto__:Bitmap.prototype,width:this.width,height:this.height,count:this.count,data:new Uint8Array(this.data)}};
Bitmap.prototype.getIntersection=function(a,b,c,d){c=c||0;d=d||0;var e=Math.max(0,c),f=Math.max(0,d);c=Math.max(0,-c);d=Math.max(0,-d);return{thisX:e,thisY:f,otherX:c,otherY:d,width:Math.max(0,Math.min(this.width-e,a-c)),height:Math.max(0,Math.min(this.height-f,b-d))}};
Bitmap.prototype.slice=function(a,b,c,d){c=this.getIntersection(a,b,c,d);b=new Bitmap(a,b);d=c.thisY*this.width+c.thisX;for(var e=c.otherY*a+c.otherX,f=0;f<c.height;f++){for(var g=0;g<c.width;g++)b.data[e]=this.data[d],d++,e++;d+=this.width-c.width;e+=a-c.width}return b};Bitmap.prototype.isZero=function(){for(var a=0;a<this.count;a++)if(this.data[a])return!1;return!0};
Bitmap.prototype.or=function(a,b,c){b=this.getIntersection(a.width,a.height,b,c);c=b.otherY*a.width+b.otherX;for(var d=b.thisY*this.width+b.thisX,e=0;e<b.height;e++){for(var f=0;f<b.width;f++)this.data[d]|=a.data[c],c++,d++;c+=a.width-b.width;d+=this.width-b.width}};
Bitmap.prototype.compare=function(a,b,c){b=this.getIntersection(a.width,a.height,b,c);c=b.otherY*a.width+b.otherX;for(var d=b.thisY*this.width+b.thisX,e=0;e<b.height;e++){for(var f=0;f<b.width;f++){if(this.data[d]&&a.data[c])return!0;c++;d++}c+=a.width-b.width;d+=this.width-b.width}return!1};Bitmap.prototype.compareMany=function(a,b,c){var d=this;return a.some(function(e){return e.x>b+d.width||e.y>c+d.height||e.x+e.bitmap.width<b||e.y+e.bitmap.height<c?!1:d.compare(e.bitmap,e.x-b,e.y-c)})};function Line(a,b,c,d){this.p1={x:a,y:b};this.p2={x:c,y:d};this.width=Math.abs(this.p1.x-this.p2.x)+1;this.height=Math.abs(this.p1.y-this.p2.y)+1;this.bitmap=null}Line.prototype.getBitmap=function(){if(this.bitmap)return this.bitmap;var a=(this.height-1)/(this.width-1);this.bitmap=new Bitmap(this.width,this.height);if(1<a)for(var b=0;b<this.height;b++)this.bitmap.set(Math.round(b/a),b,1);else for(b=0;b<this.width;b++)this.bitmap.set(b,Math.round(b*a),1);return this.bitmap};
function Rectangle(a,b){this.width=a;this.height=b;this.bitmap=null}Rectangle.prototype.getBitmap=function(){if(this.bitmap)return this.bitmap;this.bitmap=new Bitmap(this.width,this.height);for(var a=0;a<this.bitmap.count;a++)this.bitmap.data[a]=1;return this.bitmap};function AutoShape(a){this.width=a.width;this.height=a.height;this.image=a;this.bitmap=null}AutoShape.prototype.getBitmap=function(){this.bitmap||(this.bitmap=Bitmap.fromImage(this.image));return this.bitmap};var KEY_UP=38,KEY_DOWN=40,KEY_LEFT=37,KEY_RIGHT=39,KEY_JUMP=32,KEY_RESTART=82,KEY_MUTE=77,KEY_SHOOT=84,KEY_SUICIDE=81,KBD_STORAGE_KEY="keyboard_settings";
function KeyboardManager(a){this.keysPressed={};this.keyWasPressed={};this.game=a;(a=a.storage.getItem(KBD_STORAGE_KEY))?this.gameKeys=a:this.resetKeys();window.addEventListener("keydown",this.onkeydown.bind(this),!1);window.addEventListener("keyup",this.onkeyup.bind(this),!1);window.addEventListener("blur",this.onblur.bind(this),!1);var b=this,c=0;document.getElementById("reset_keys").addEventListener("click",function(){this.textContent="Done.;Keys resetted.;You keep failing at this, huh?;undefined;Just kidding.;Bored?;Okay ...;There once was a girl from Kentucky ...".split(";")[c++];
8===c&&(location.href="https://www.youtube.com/watch?v=oHg5SJYRHA0");b.resetKeys();b.saveSettings()},!1);[["left",KEY_LEFT],["right",KEY_RIGHT],["shoot",KEY_SHOOT],["jump",KEY_JUMP],["mute",KEY_MUTE],["restart",KEY_RESTART]].forEach(function(d){var e=d[1];d=document.getElementById("change_"+d[0]);var f=document.getElementById("keys"),g=document.getElementById("press_key_msg");d.addEventListener("click",function(){f.style.display="none";g.style.display="block";window.addEventListener("keydown",function l(k){27!==
k.which&&(Object.deleteByValue(b.gameKeys,e),b.gameKeys[k.which]=e,b.saveSettings());window.removeEventListener("keydown",l,!1);f.style.display="block";g.style.display="none";k.preventDefault()},!1)},!1)})}KeyboardManager.prototype.resetKeys=function(){this.gameKeys={38:KEY_UP,40:KEY_DOWN,37:KEY_LEFT,39:KEY_RIGHT,32:KEY_JUMP,82:KEY_RESTART,77:KEY_MUTE,84:KEY_SHOOT,81:KEY_SUICIDE}};KeyboardManager.prototype.saveSettings=function(){this.game.storage.setItem(KBD_STORAGE_KEY,this.gameKeys)};
KeyboardManager.prototype.isValid=function(a){return!(a.ctrlKey||a.altKey||a.metaKey||a.target instanceof HTMLTextAreaElement||a.target instanceof HTMLInputElement||!this.gameKeys[a.which])};KeyboardManager.prototype.onkeydown=function(a){this.keysPressed[a.which]?a.preventDefault():this.isValid(a)&&(this.keysPressed[a.which]=!0,this.handleKey(!1,a.which),a.preventDefault())};KeyboardManager.prototype.onkeyup=function(a){this.isValid(a)&&(this.keysPressed[a.which]=!1,this.handleKey(!0,a.which),a.preventDefault())};
KeyboardManager.prototype.onblur=function(){for(var a=Object.keys(this.keysPressed),b=0;b<a.length;b++){var c=a[b];this.keysPressed[c]&&this.handleKey(!0,Number(c))}this.keysPressed={}};KeyboardManager.prototype.handleKey=function(a,b){b=this.gameKeys[b];b===KEY_MUTE?a||this.game.toggleMute():b===KEY_RESTART&&(a||this.game.restart());b===KEY_SUICIDE?a||this.game.die():this.keyWasPressed[b]=!a};window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame);function GameRenderer(a){var b=document.getElementById("canvas");this.context=b.getContext("2d");b.width=a.width;b.height=a.height;this.canvas=b;this.backgroundCanvas=null;this.animationTick=0;this.animations={};this.game=a}
GameRenderer.prototype.loadBackground=function(a){this.backgroundCanvas=this.imagesToCanvas(a,this.game.level.width,this.game.level.height,this.game.level.backgroundColor)};GameRenderer.prototype.loadForeground=function(a){this.foregroundCanvas=this.imagesToCanvas(a,this.game.level.width,this.game.level.height)};
GameRenderer.prototype.imagesToCanvas=function(a,b,c,d){var e=document.createElement("canvas"),f=e.getContext("2d");e.width=b;e.height=c;d&&(f.fillStyle=d,f.fillRect(0,0,b,c));a.forEach(function(g){f.drawImage(g.image,g.x,g.y,g.width,g.height)});return e};GameRenderer.prototype.drawAnimation=function(a,b,c){a=this.game.level.animations[a];this.context.drawImage(this.game.images[a.images[(this.animationTick/a.time|0)%a.images.length]],b,c)};
GameRenderer.prototype.drawImageOrAnimation=function(a,b,c){this.game.level.animations[a]?this.drawAnimation(a,b,c):this.context.drawImage(this.game.images[a],b,c)};
GameRenderer.prototype.redraw=function(){var a=this.context,b=this.game,c=b.images;this.animationTick++;a.drawImage(this.backgroundCanvas,b.viewportX,b.viewportY,b.width,b.height,0,0,b.width,b.height);if(!b.dead){var d="char";b.fallingState===NOT_FALLING?b.isMoving&&(d+="Moving"):d=0<b.vspeed?d+"Falling":d+"Jumping";d=b.direction==LEFT?d+"Left":d+"Right";this.drawImageOrAnimation(d,b.posX-b.viewportX,b.posY-b.viewportY)}b.drawableObjects.forEach(function(e){e.visible&&e.x+e.width>=b.viewportX&&e.x<
b.viewportX+b.width&&e.y+e.height>=b.viewportY&&e.y<b.viewportY+b.height&&a.drawImage(e.image,Math.round(e.x-b.viewportX),Math.round(e.y-b.viewportY),e.width,e.height)});b.dead&&a.drawImage(c.gameOver,0,150);a.fillStyle="rgba(0,0,0,"+(b.keysDown[0]?"1":"0.3")+")";a.fillRect(10,b.height-70,50,50);a.fillStyle="rgba(0,0,0,"+(b.keysDown[1]?"1":"0.3")+")";a.fillRect(60,b.height-120,50,50);a.fillStyle="rgba(0,0,0,"+(b.keysDown[2]?"1":"0.3")+")";a.fillRect(110,b.height-70,50,50)};
GameRenderer.prototype.drawLoadingScreen=function(a,b){this.context.fillStyle="#000";this.context.fillRect(0,0,this.game.width,this.game.height);this.context.fillStyle="#fff";this.context.font="20px monospace";this.context.textAlign="center";this.context.fillText("Loading resources. Please wait ...",this.game.width>>1,100);this.context.fillText(a+" out of "+b,this.game.width>>1,140)};Math.sign=function(a){return(0<a)-(0>a)};Math.roundInfinity=function(a){return 0<a?Math.ceil(a):Math.floor(a)};Math.floatToRandom=function(a){var b=Math.floor(a);return b+(Math.random()>a-b)};Math.triangle=function(a){return function(b){b/=a;return-1+4*Math.abs(b+.25-Math.floor(b+.75))}};Math.rectangle=function(a){var b=Math.triangle(a);return function(c){return Math.sign(b(c))}};Math.compare=function(a,b){return Math.sign(a-b)};
Array.prototype.findIndex=function(a){var b;this.some(function(c,d){if(a(c))return b=d,!0});return b};Array.prototype.find=function(a){a=this.findIndex(a);if(void 0!==a)return this[a]};Array.prototype.delete=function(a){a=this.indexOf(a);return-1!==a?this.slice(0,a).concat(this.slice(a+1)):this};Array.prototype.concatMap=function(a){var b=[];this.forEach(function(c){b=b.concat(a(c))});return b};Array.prototype.deleteList=function(a){return this.filter(function(b){return-1===a.indexOf(b)})};
Array.replicate=function(a,b){for(var c=[],d=0;d<a;d++)c[d]=b;return c};Array.prototype.partition=function(a){return this.reduce(function(b,c){a(c)?b[0].push(c):b[1].push(c);return b},[[],[]])};Array.toArray=function(a){return[].slice.call(a)};Function.byIndex=function(a,b){return function(c){return c[a]===b}};
Object.deepcopy=function clone(a){if("object"===typeof a){if(a instanceof Array)return a.map(clone);if(a.__proto__)for(var c={__proto__:a.__proto__},d=Object.keys(a),e=0;e<d.length;e++)c[d[e]]=a[d[e]];else for(d in c={},a)c[d]=clone(a[d]);return c}return a};Object.isArray=function(a){return a instanceof Array};Function.not=function(a){return function(b){return!a(b)}};function range(a,b,c){var d=[];c=c||1;dbg_assert(0<c);void 0===b&&(b=a,a=0);for(;a<b;a+=c)d.push(a);return d}
Function.hook=function(a,b,c){var d=a[b];a[b]=function(){d.apply(this,arguments);c.apply(this,arguments)}};Object.extend=function(a,b){for(var c=Object.keys(b),d,e=0;e<c.length;e++)d=c[e],a[d]=b[d];return a};Object.deleteByValue=function(a,b){for(var c=Object.keys(a),d=0;d<c.length;d++)a[c[d]]===b&&delete a[c[d]]};Object.merge=function(a,b){return Object.extend(Object.extend({},a),b)};Object.values=function(a){for(var b=Object.keys(a),c=[],d=0;d<b.length;d++)c.push(a[b[d]]);return c};
function dbg_log(a){document.getElementById("debug").textContent=a}function dbg_warn(a){document.getElementById("warn").textContent+=a+"\n"}function dbg_assert(a,b){if(!a)throw console.trace(),"Assert failed: "+b;}function http_get(a,b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){4===d.readyState&&(200===d.status?b(d.responseText,a):c&&c(d.responseText,d.status))};d.open("get",a,!0);d.send("");return{cancel:function(){d.abort()}}}
function cartesianProductOnObjects(a,b){Object.isArray(a)||(a=[a]);return b.reduce(function(c,d){return c.concatMap(function(e){var f=e[d];return Object.isArray(f)?f.map(function(g){var h=Object.deepcopy(e);h[d]=g;return h}):[e]})},a)};+function(){var a="";window.addEventListener("keyup",function(b){a=(a+b.which).substr(-14);83677278798377==a&&(localStorage.last_level='"2up.js"',localStorage.removeItem("state"),location.reload())},!1)}();
